#!/usr/bin/env php
<?php
require_once("/../vendor/autoload.php");
use Symfony\Component\Console\Application;
use Plunder\Command\TesteCommand;
use Plunder\Command\TestarCommand;
use Plunder\Command\ReverseCommand;
use Plunder\Command\BuildCommand;

$application = new Application();
$application->add(new TesteCommand);
$application->add(new ReverseCommand );
$application->add(new BuildCommand );
$application->run();